<a href="https://colab.research.google.com/github/brianadit24/RecSysTourist/blob/main/RecSys_Tourist_on_Jogja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Module

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

In [30]:
rating = pd.read_csv('ratings.csv')
destination = pd.read_csv('dataset.csv', index_col='index')

# Dataset Info

In [ ]:
rating.head()

user_id  index  ratings
0        1     31        1
1        1     29        5
2        1     91        4
3        1      3        4
4        1     37        1

In [31]:
destination.head()

nama  ...                                        description
index                                                 ...                                                   
0                                    Candi Borobudur  ...  Candi yang pernah masuk sebagai salah satu dar...
1                                    Candi Prambanan  ...  Candi Prambanan adalah kompleks candi Hindu te...
2                                      Tebing Breksi  ...  Tebing Breksi merupakan tempat wisata yang ber...
3                                   Gembira Loka Zoo  ...  Gambira Loka adalah kebun binatang yang berada...
4      The Palace of Yogyakarta (Keraton Yogyakarta)  ...  Kompleks keraton merupakan museum yang menyimp...

[5 rows x 9 columns]

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15029 entries, 0 to 15028
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  15029 non-null  int64
 1   index    15029 non-null  int64
 2   ratings  15029 non-null  int64
dtypes: int64(3)
memory usage: 352.4 KB


In [ ]:
destination.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   index         142 non-null    int64  
 1   nama          142 non-null    object 
 2   vote_average  142 non-null    float64
 3   vote_count    142 non-null    int64  
 4   type          142 non-null    object 
 5   htm_weekday   128 non-null    float64
 6   htm_weekend   125 non-null    float64
 7   latitude      142 non-null    float64
 8   longitude     142 non-null    float64
 9   description   142 non-null    object 
dtypes: float64(5), int64(2), object(3)
memory usage: 11.2+ KB


In [43]:
dest_rating = pd.merge(rating, destination, on='index')
cols = ['vote_average', 'vote_count', 'type', 'htm_weekday', 'htm_weekend', 'latitude', 'longitude', 'description']
dest_rating.drop(cols, axis=1, inplace=True)
dest_rating.sort_values("user_id")

user_id  index  ratings                       nama
0            1     31        1   De Mata Trick Eye Museum
91           1     29        5  Agro Tourism Bhumi Merapi
92           1     29        2  Agro Tourism Bhumi Merapi
752          1     68        2           Balong Waterpark
200          1     91        4     Kids Fun Galleria Mall
...        ...    ...      ...                        ...
8730      1000     66        3         Bukit Lintang Sewu
14000     1000    104        5               Museum Sandi
10345     1000     59        4           Pantai Sepanjang
2205      1000     69        1      Kids Fun Park (Pusat)
6486      1000    134        2        Tebing Gunung Gajah

[15029 rows x 4 columns]

# Content Base Filtering

In [1]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize

In [5]:
destination.head()

index  ...                                        description
0      0  ...  Candi yang pernah masuk sebagai salah satu dar...
1      1  ...  Candi Prambanan adalah kompleks candi Hindu te...
2      2  ...  Tebing Breksi merupakan tempat wisata yang ber...
3      3  ...  Gambira Loka adalah kebun binatang yang berada...
4      4  ...  Kompleks keraton merupakan museum yang menyimp...

[5 rows x 10 columns]

## Encode All Synopsis to Bank

In [9]:
bow = CountVectorizer(tokenizer=word_tokenize)
bank = bow.fit_transform(destination.description)

## Step 1 : Encode what user watch

In [10]:
idx = 0

In [12]:
content = destination.loc[idx, "description"]
content

'Candi yang pernah masuk sebagai salah satu dari Tujuh Keajaiban Dunia ini dihiasi oleh banyak relief di dinding candi. Relief yang ada di Candi Borobudur mencapai 2.672 dan panjangnya bisa mencapai 6 kilometer'

In [14]:
code = bow.transform([content])
code.toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

## Step 2: Document Search

In [15]:
from sklearn.metrics.pairwise import cosine_distances

In [16]:
dist = cosine_distances(code, bank)
dist

array([[0.        , 0.59035598, 0.67697086, 0.8502479 , 0.77549337,
        0.791122  , 0.67688484, 0.70103726, 0.76614641, 0.82337603,
        0.79868094, 0.75381702, 0.69591818, 0.79587585, 0.6555405 ,
        0.88129087, 0.84508067, 0.75485483, 0.69481069, 0.6680236 ,
        0.63216903, 0.82109339, 0.82735773, 0.75256417, 0.75338999,
        0.72222222, 0.78240293, 0.77917258, 0.58528898, 0.72860835,
        0.72499045, 0.75769416, 0.6095008 , 0.77411867, 0.79911847,
        0.76381125, 0.75266716, 0.71909968, 0.76793022, 0.74599975,
        0.74379495, 0.71464945, 0.78498168, 0.89174682, 0.74523767,
        0.75168352, 0.75945129, 0.70066696, 0.80372678, 0.91091292,
        0.70984066, 0.90871291, 0.68484238, 0.66735043, 0.72531936,
        0.77569114, 0.78464724, 0.79542073, 0.66321234, 0.75485483,
        0.50257512, 0.78959365, 0.91116637, 0.71301799, 0.72808762,
        0.77848059, 0.7369316 , 0.80949981, 0.7658419 , 1.        ,
        0.78080135, 0.69734004, 0.84409761, 0.74

In [37]:
rect_idx = dist.argsort()
rect_idx

array([[  0, 108, 119,  60, 100,  76,  28,   1,  32,  20, 114, 140,  14,
        113,  58,  53,  19,  85,  78, 105,   6,   2, 138, 135,  99,  52,
         79,  82,  18, 109,  12,  71,  47, 124,   7,  50,  74,  80,  94,
         63,  84,  41,  37,  25,  81, 115,  30,  54,  98,  64,  29, 121,
         66,  96,  95, 120,  73, 125,  40,  91,  44, 129,  39, 122,  45,
        130,  23,  36,  24,  11,  59,  17,  31,  46,  97, 106,  35, 104,
         68,   8, 103,  38, 118, 117,  33,   4,  55,  77,  65,  27, 111,
         70, 116,  88,  26, 133,  56,  42,  87,  61,   5, 136,  57,  13,
        123,  10,  34, 107,  48, 141,  67, 134, 102,  86,  75,  21,  89,
         90,   9, 132, 139, 110,  22, 131,  72,  16,  93,   3,  92, 112,
        127, 101,  15,  43,  83, 126, 128,  51,  49,  62,  69, 137]])

## Step 3: Recommend

In [18]:
destination.loc[rect_idx]

index  ...                                        description
108    108  ...  Candi Banyunibo adalah candi Buddha yang berad...
119    119  ...  Candi Sari juga disebut Candi Bendah adalah ca...
60      60  ...  Candi Sewu adalah candi Buddha yang dibangun p...
100    100  ...  Candi Kalasan adalah candi yang dipersembahkan...
76      76  ...  Candi Sojiwan memiliki keunikan. Keunikan ini ...
28      28  ...  Candi Plaosan terletak di Desa Bugisan, Kecama...
1        1  ...  Candi Prambanan adalah kompleks candi Hindu te...
32      32  ...  Candi Sambisari adalah Candi Hindu yang berada...
20      20  ...  Pantai Depok yang letaknya hanya 1,5 km dari P...

[9 rows x 10 columns]

## ML Engineering: Content Base Filtering

In [33]:
class ContentRecSys:
    def __init__(self, data, content_col, index_col=None):
        self.df = pd.read_csv(data, index_col=index_col)
        self.content_col = content_col
        self.encoder = None
        self.bank = None

    def fit(self):
        self.encoder = CountVectorizer(tokenizer=word_tokenize)
        self.bank = self.encoder.fit_transform(self.df[self.content_col])

    def recommend(self, idx, topk=10):
        content = self.df.loc[idx, self.content_col]
        code = self.encoder.transform([content])
        dist = cosine_distances(code, self.bank)
        rect_idx = dist.argsort()[0, 1:(topk+1)]
        return self.df.loc[rect_idx]

## Testing Content Base Filtering

In [34]:
conrecsys = ContentRecSys(data="dataset.csv", content_col="description", index_col='index')
conrecsys.fit()

In [35]:
conrecsys.recommend(20) # Depok Beach

nama  ...                                        description
index                      ...                                                   
58        Pantai Ngandong  ...  Pantai ini memiliki garis pantai yang panjang ...
96        Pantai Ngrumput  ...  Pantai Ngrumput memang kalah pamor dengan Para...
52     Pantai Pok Tunggal  ...  Pantai Pok Tunggal adalah salah satu pantai po...
82       Pantai Ngrenehan  ...  Pantai Ngrenehan merupakan pantai nelayan. Ter...
64          Pantai Timang  ...  Begitu memasuki wilayah pantai, pengunjung aka...
109       Pantai Nglolang  ...  Pantai ini sangat indah dengan pasir putih dan...
135        Bukit Pengilon  ...  Nama bukit Pengilon berasal dari bahasa Jawa y...
97          Pantai Ngedan  ...  Pantai Ngeden atau Ngedan yang terletak di Des...
105     Bukit Teletubbies  ...  Wisata satu ini merupakan wisata yang lokasiny...
53        Pantai Ngobaran  ...  Keunikan yang menjadi ciri khas Pantai Ngobara...

[10 rows x 9 columns]

In [36]:
conrecsys.recommend(4) # Keraton Jogja

nama  ...                                        description
index                                      ...                                                   
86             Puncak Kebun Buah Mangunan  ...  Objek wisata ini menawarkan keindahan berupa p...
15                      Pantai Goa Cemara  ...  Adalah Kawasan Wisata Terpadu, satu pintu deng...
136                  Taman Tempuran Cikal  ...  Taman Tempuran Cikal terletak di kecamatan Piy...
84                         Affandi Museum  ...  Museum Affandi merupakan salah satu museum sen...
88               Museum Sonobudoyo Unit I  ...  useum Sonobudoyo unit pertama yang ada di deka...
85     Museum Monumen Pangeran Diponegoro  ...  Museum Monumen Pangeran Diponegoro adalah muse...
65                     Museum HM Soeharto  ...  Museum Soeharto adalah adalah bangunan berBuda...
90                   Kawasan Pantai Baron  ...  Objek wisata Pantai Baron merupakan pantai yan...
67                   Grand Puri Waterpark  ...  Grand Puri Waterpark Yogya berlokasi di daerah...
9                   The Lost World Castle  ...  Di dalam The Lost World Casle, pengunjung disu...

[10 rows x 9 columns]